name: Auto Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 51.21.131.90
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/-KUREMEDI-LUCENT-Project
            git pull origin main
            cd backend
            npm install
            pm2 restart lucent-backend
