name: Deploy Node Backend to EC2

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd -KUREMEDI-LUCENT-Project/backend
            git pull origin main
            npm install
            pm2 restart backend || pm2 start index.js --name backend
