name: Build Expo APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend/app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Expo
        run: npm install -g expo-cli

      - name: Install deps
        run: npm install

      - name: Build Android
        run: |
          npx expo prebuild --platform android
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: Frontend/app/android/app/build/outputs/apk/release/app-release.apk
