name: Deploy Frontend (Next + Admin)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.FRONTEND_EC2_HOST }}
        username: ${{ secrets.FRONTEND_EC2_USER }}
        key: ${{ secrets.FRONTEND_EC2_KEY }}
        script: |
          cd /home/ubuntu

          # Clone if not exists
          if [ ! -d "-KUREMEDI-LUCENT-Project" ]; then
            git clone https://github.com/ankurkushwaha809/-KUREMEDI-LUCENT-Project.git
          fi

          cd -KUREMEDI-LUCENT-Project

          git pull origin main

          # -------- WEBSITE (Next.js) --------
          cd website
          npm install
          npm run build
          pm2 restart website || pm2 start npm --name website -- start

          # -------- ADMIN (Vite React) --------
          cd ../Frontend/admin
          npm install
          npm run build
          pm2 restart admin || pm2 start serve --name admin -- -s dist -l 5173

          pm2 save
