name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.FRONTEND_USER }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          script: |
            cd ~

            if [ ! -d "-KUREMEDI-LUCENT-Project" ]; then
              git clone https://github.com/ankurkushwaha809/-KUREMEDI-LUCENT-Project.git
            fi

            cd -KUREMEDI-LUCENT-Project
            git fetch origin
            git reset --hard origin/main

            echo "Build Website"
            cd Frontend/website
            npm install
            npm run build
            pm2 delete website || true
            pm2 start npm --name website -- start

            echo "Build Admin"
            cd ../admin
            pnpm install
            pnpm build
            pm2 delete admin || true
            pm2 start npm --name admin -- start -- --host 0.0.0.0

            pm2 save
            pm2 list
